apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-postgres
  labels:
    app: event-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-postgres
  template:
    metadata:
      labels:
        app: event-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: livepass
            - name: POSTGRES_PASSWORD
              value: livepass
            - name: POSTGRES_DB
              value: livepass_events
---
apiVersion: v1
kind: Service
metadata:
  name: event-postgres
  labels:
    app: event-postgres
spec:
  type: ClusterIP
  selector:
    app: event-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-postgres
  labels:
    app: booking-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-postgres
  template:
    metadata:
      labels:
        app: booking-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: livepass
            - name: POSTGRES_PASSWORD
              value: livepass
            - name: POSTGRES_DB
              value: livepass_bookings
---
apiVersion: v1
kind: Service
metadata:
  name: booking-postgres
  labels:
    app: booking-postgres
spec:
  type: ClusterIP
  selector:
    app: booking-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
